### PR TITLE
Suggested changes

### PR DESCRIPTION
**Pull request by guekho64**
Just some improvements on the original idea: Hope you can add then to your original pull request.

Had no other choice rather than creating another `apt-fast` fork and creating a pull request towards your fork, as I have no write access at `apt-fast` original repo.

### CODE REVIEW

**Comment by dityaaa** [comment]
Ahh sorry I just saw this. Let me take a look

**Comment by dityaaa** [comment]
I don't think preserving .aria2 from a corrupted download is good
I got a chance to take a look at .aria2 control file [in this link](https://github.com/ilikenwf/apt-fast/pull/184#issuecomment-750859054). Apparently, incomplete download and corrupted download have different data.
So I think we need to remove only the corrupted file and it's .aria2 control file, but preserving incomplete download.
What do you think?

**Comment by guekho64** [comment]
@dityaaa While your original idea it's practically untouched, I implement it slightly different, as it follows:

1- First, check if there are any `.aria2` files in `"$DLDIR"` by using the `find` command, which is slightly faster than bash when finding files, as it was designed to specifically do so;  Also, `"$DLDIR"` holds the actual value of the download directory in use by `apt-fast`, (Which can be configured either using `dpkg-reconfigure "apt-fast"` or directly editing `/etc/apt-fast.conf`) in a non-recursive manner, because `apt-fast` _does not_ expect any directories to exist within `"$DLDIR"`: If any directories actually exist within `"$DLDIR"`, they will be ignored (Rather than exiting/crashing).

2- After that, it'll proceed to actually delete both `.aria2` and `.deb` files (Which may belong to either corrupted files and/or incomplete files) by using your approach, while adding `-fv` flags to force delete & tell `rm` to output info about each file being deleted: Obviously, as this info isn't intended to be shown in a production release, a pipe to `/dev/null` redirects both `stdout` & `stderr` from `rm` to `/dev/null`, effectively hiding all this info to final users. Devs can comment out such pipe to bring back debug info.

As a side note, I could have re-implemented the second point by using `find` as well, but it turned out to be more tedious than I initially though, mainly due to `bash` having its own `"$IFS"` (Internal Field Separator), which can cause issues when bash receives data which contain special characters, such as `\n`, and I only know two options to workaround this behavior:

* Temporally override/delete `"$IFS"  variable, and restore it at a later point (If it isn't restored later, bash might break).
* Do what I commented out in the code.

Either way, both seemed way too complex for what their purpose was, so I went back using your approach, considering Debian Package names _usually_ don't contain `spaces` neither `newlines` in them. (I dunno if there's a convention for them: I'm not a package maintainer).

Also, and as a side effect from using `find` rather than `test` to find files in `"$DLDIR"`, it should not suffer from https://github.com/ilikenwf/apt-fast/pull/185.

**Comment by guekho64** [comment]
> I don't think preserving .aria2 from a corrupted download is good
> I got a chance to take a look at .aria2 control file [in this link](https://github.com/ilikenwf/apt-fast/pull/184#issuecomment-750859054). Apparently, incomplete download and corrupted download have different data.
> So I think we need to remove only the corrupted file and it's .aria2 control file, but preserving incomplete download.
> What do you think?

I also forgot to mention that `aria2c` automatically deletes "orphan" `.aria2` files, although `rm "$x" "${x%.*}"` already removes both `.aria2` and `.deb` files at once.

**Comment by dityaaa** [comment]
>
>
> 1- First, check if there are any .aria2 files in "$DLDIR" by using the find command, which is slightly faster than bash when finding files, as it was designed to specifically do so; Also, "$DLDIR" holds the actual value of the download directory in use by apt-fast, (Which can be configured either using dpkg-reconfigure "apt-fast" or directly editing /etc/apt-fast.conf) in a non-recursive manner, because apt-fast does not expect any directories to exist within "$DLDIR": If any directories actually exist within "$DLDIR", they will be ignored (Rather than exiting/crashing).

Ahh yes I understand it now. Previously, I try to implement file removal with find and sed, but I got stuck with rm command. 

image
Filename is filtered successfully, but I got an error when I try to remove with xargs rm, said file isn't found. That's why I use my current implementation.
I'm not really familiar with Linux command, sorry.

**Comment by guekho64** [comment]
@dityaaa No need to be sorry, I'm not a Linux professional neither, nor an `apt-fast` maintainer: I just do what I know to help.

Related to your problem, I also got stuck trying to use `rm` alongside `find` as you did, so I came up with this:

``` bash

while read -r file; do
    rm $(printf '%s %s' "$file" "$(printf '%s' "$file" | sed -E 's/\.aria2$/.deb/g')")
done <<< $(find '.''' -maxdepth '1' -type 'f' -name '*.aria2' | sort -u)

```

which actually works, but it seemed way too complex just to delete a bunch of files, so I went back to your idea. We could also have used `find` with `-exec` flag, bue due to bash's nature, we might have to end up using `eval` as well, which [is said to be evil](https://stackoverflow.com/questions/17529220/why-should-eval-be-avoided-in-bash-and-what-should-i-use-instead): For that reason, I prefer to stay as far as possible from it.

`xargs` might have worked too: Maybe you just used `"$(... | xargs ...)"` rather than `$(... | xargs ...)` (Please note the abscence of double quotes)

**Comment by dityaaa** [comment]
@guekho64 Thanks for your suggestion, now I successfully implement rm with find.
Like your suggestion, I use `-fv`, with `maxdepth` of 1 and redirect all output to `/dev/null`

`rm -fv $(find '.' -maxdepth '1' -type f -name '*.aria2' | sed 's/\.aria2$/*/') > /dev/null 2>&1`

image

What do you think of this?

**Comment by guekho64** [comment]
Sorry for the delay replying: I've been a bit busy lately.

About your implementation, I find it quite simple yet effective, so nice work! Admittedly, I didn't think about using shell expansion to my favour, like you did, which makes your one-liner as fast as possible.

However, there's a small pitfall when using shell expansion to feed a dynamic amount of arguments into another command (In this case `rm`):

* Bash (And probably any other shell that exists) [has a limit](https://www.in-ulm.de/~mascheck/various/argmax/) regarding how many arguments a command (Or function) can receive, throwing an error in case you reach it.

For instance, `xargs --show-limits` shows some information about the aforementioned limit _on your system_: Being a variable, it _is_ prone to change (Or even disappear in some systems, which would mean there's no limit).

Of course, as you might have already guessed, _usually_ this value it's quite high (~1000+), but there are no guarantees on it (As far as I know), so, in most cases, your command would run faster than mine, as long as you don't reach bash's argument limit, which would trigger a `rm: arg list too long` error.

So, given the above, and due to my past experiences, whenever I have to decide between writing safe code or writing fast code, I always choose safe code, and that's exactly why I went back to your initial approach, with very little changes.

* Uses a `for` loop (`for x in *.aria2` -> Immune to ARG_MAX limit)
* `rm`, it's always provided with 2 arguments at most, at any time. (`"$x" "${x%.aria2}"`)

Unfortunately, this invokes a lot of `rm` commands, depending of the amount of `.aria2` files found by bash, which obviously slow things down a bit, but at least it's 100% safe to use.

BTW, I'm closing this PR, as this has become kind of a duplicate of [#186](https://github.com/ilikenwf/apt-fast/pull/186)

**Pull request closed without merging**
